import type { VocabWord } from './types';

// ---------------------------------------------------------------------------
// THE BOOK, TRANSCRIBED.
//
// Source: 『英熟語ターゲット1000』 Day 31-35 (No. 481-560, pp.162-181),
// photographed by the user and read off the pages.
//
// WHAT CAME FROM THE BOOK AND WHAT DID NOT
//   `en`, `ja`, `jaFull` and the ≒ cross-references in `synonymIds` are the
//   book's. `ja` in particular is its own Quick Review wording rather than an
//   abbreviation invented here, so a quiz choice is phrased the way the reader
//   has already been drilled on.
//
//   `note`, `tip` and `example` are NOT in the book -- they are written here, to
//   answer "why does it mean that" and "what actually catches people out". They
//   are shown only AFTER an answer is given, so they never leak the answer.
//
// DO NOT CHANGE AN `id`. It is a stored key; see shared/vocabulary/types.ts.
// ---------------------------------------------------------------------------

export const VOCAB_WORDS: readonly VocabWord[] = [
  // === Day 31 — 動詞句4「動詞＋副詞［前置詞］」型4 ===
  {
    id: 'et-481',
    number: 481,
    day: 31,
    en: 'come from',
    ja: '〜に由来する',
    jaFull: '❶〜に由来する ❷〜の出身である',
    note: 'come（来る）＋ from（〜から）。「〜から来ている」が字義で、そこから「出どころは〜だ」＝由来にも出身にもなる。',
    tip: '出身を言うときは現在形 I come from Osaka. が普通。過去形 I came from Osaka. だと「大阪から（今）来たところだ」という移動の話になってしまう。',
    example: {
      en: 'The word "tsunami" comes from Japanese.',
      ja: '「tsunami」という語は日本語に由来する。',
    },
  },
  {
    id: 'et-482',
    number: 482,
    day: 31,
    en: 'cut down',
    ja: '〜を切り倒す',
    jaFull: '〜を切り倒す、伐採する',
    note: 'cut（切る）＋ down（下へ）。立っているものを切って下に倒すイメージ。',
    tip: 'on をひとつ足して cut down on 〜 にすると「〜を減らす・控える」（cut down on sugar）。前置詞ひとつで意味が変わる。',
    example: {
      en: 'They cut down the old tree in the garden.',
      ja: '彼らは庭の古い木を切り倒した。',
    },
  },
  {
    id: 'et-483',
    number: 483,
    day: 31,
    en: 'fall down',
    ja: '転ぶ',
    jaFull: '転ぶ、倒れる',
    note: 'fall（落ちる）＋ down（下へ）。人なら「転ぶ」、物なら「倒れる・崩れる」。',
    tip: '自動詞なので目的語を取らない。「〜を倒す」と言いたいなら knock down。fall off（489）と混ぜないこと——あちらは「乗っていた物から落ちる」。',
    example: {
      en: 'Be careful not to fall down on the ice.',
      ja: '氷の上で転ばないように気をつけて。',
    },
  },
  {
    id: 'et-484',
    number: 484,
    day: 31,
    en: 'get back',
    ja: '戻る',
    jaFull: '（〜から／…に）戻る、帰る（from 〜／to …）（≒ return, come back）',
    note: 'get（至る）＋ back（元へ）。元いた場所へ自分が戻る。',
    tip: 'get back to 人 は「（人）に後で返事をする」の定番。I\'ll get back to you.＝「追って連絡します」。',
    example: {
      en: 'What time did you get back home last night?',
      ja: '昨夜は何時に家に戻ったの。',
    },
  },
  {
    id: 'et-485',
    number: 485,
    day: 31,
    en: 'get in',
    ja: '中へ入る',
    jaFull: '中へ入る',
    note: 'get（至る）＋ in（中へ）。車やタクシーのような狭い乗り物に乗り込むときもこれ。',
    tip: '乗り物は屈んで入るか、またいで乗るかで前置詞が変わる。車＝get in / get out、電車・バス・飛行機＝get on / get off。',
    example: {
      en: "Get in — I'll drive you to the station.",
      ja: '乗って、駅まで送るよ。',
    },
  },
  {
    id: 'et-486',
    number: 486,
    day: 31,
    en: 'knock on',
    ja: '〜をノックする',
    jaFull: '〜をノックする（knock at も可）',
    note: 'knock（叩く）＋ on（接触）。ドアの面に触れて叩く。',
    tip: 'knock at でも同じ意味。on のほうが「面を叩く」感じが強く、現代英語では優勢。',
    example: {
      en: 'Someone is knocking on the door.',
      ja: '誰かがドアをノックしている。',
    },
  },
  {
    id: 'et-487',
    number: 487,
    day: 31,
    en: 'look around',
    ja: '〜を見て回る',
    jaFull: '〜を見て回る［歩く］',
    jaAlt: ['〜を見て歩く'],
    note: 'look（見る）＋ around（周囲を）。ぐるりと見渡す、店や街を見て回る。',
    tip: '目的語なしでも使えて「あたりを見回す」。買い物で「見ているだけです」は I\'m just looking around.',
    example: {
      en: 'We spent the afternoon looking around the old town.',
      ja: '午後は旧市街を見て回った。',
    },
  },
  {
    id: 'et-488',
    number: 488,
    day: 31,
    en: 'bring back',
    ja: '〜を返す',
    jaFull: '〜を（…に）返す（to …）（≒ return, give back）',
    note: 'bring（持ってくる）＋ back（元へ）。借りた物を持ち主のところへ持って戻る。',
    tip: 'take back（496）と方向が逆。話し手のいる場所へ戻すのが bring back。「思い出させる」の意味も頻出（The song brings back memories.）。',
    example: {
      en: 'Please bring back the book by Friday.',
      ja: '金曜までにその本を返してください。',
    },
  },
  {
    id: 'et-489',
    number: 489,
    day: 31,
    en: 'fall off',
    ja: '〜から落ちる',
    jaFull: '〜から落ちる',
    note: 'fall（落ちる）＋ off（離れて）。くっついていた／乗っていたものから外れて落ちる。',
    tip: 'fall down（483）は「その場で転ぶ」。落ちる元があるかどうかで使い分ける。',
    example: {
      en: 'He fell off his bike and hurt his knee.',
      ja: '彼は自転車から落ちて膝を痛めた。',
    },
  },
  {
    id: 'et-490',
    number: 490,
    day: 31,
    en: 'pay for',
    ja: '〜の支払いをする',
    jaFull: '〜の支払いをする、代金を払う',
    note: 'pay（払う）＋ for（〜と引き換えに）。for の後ろは買う物やサービス。',
    tip: '金額そのものには for を付けない（pay 3,000 yen）。「人にBの代金を払う」は pay A for B（511）。',
    example: {
      en: "I'll pay for dinner tonight.",
      ja: '今夜の夕食は私が払うよ。',
    },
  },
  {
    id: 'et-491',
    number: 491,
    day: 31,
    en: 'put away',
    ja: '〜を片づける',
    jaFull: '〜を（元の所へ）片づける、しまう',
    note: 'put（置く）＋ away（離れた所へ）。使った物を定位置へ戻す。',
    tip: '「捨てる」ではない——捨てるは throw away。代名詞を目的語にするときは put it away の語順で、put away it とは言えない。',
    example: {
      en: 'Put away your toys before dinner.',
      ja: '夕食の前におもちゃを片づけなさい。',
    },
  },
  {
    id: 'et-492',
    number: 492,
    day: 31,
    en: 'work on',
    ja: '〜に取り組む',
    jaFull: '〜に取り組む',
    note: 'work（働く）＋ on（接触して）。対象にずっと手をかけている状態。',
    tip: '完成は含意しない。I\'m working on it.＝「今やっているところ（まだ終わっていない）」。',
    example: {
      en: 'She is working on her graduation thesis.',
      ja: '彼女は卒業論文に取り組んでいる。',
    },
  },
  {
    id: 'et-493',
    number: 493,
    day: 31,
    en: 'cool down',
    ja: '〜を冷やす',
    jaFull: '〜を冷やす、冷ます',
    note: 'cool（冷たくする）＋ down（下へ）。温度を下げる。',
    tip: '他動詞（〜を冷やす）でも自動詞（冷める）でも使える。人が主語なら「頭を冷やす・落ち着く」（Cool down!）。',
    example: {
      en: 'Cool the soup down before you eat it.',
      ja: '食べる前にスープを冷ましなさい。',
    },
  },
  {
    id: 'et-494',
    number: 494,
    day: 31,
    en: 'look after',
    ja: '〜の世話をする',
    jaFull: '〜の世話をする、面倒を見る（≒ take care of）',
    note: 'look（目を向ける）＋ after（後を追って）。後ろからずっと目を離さない＝世話をする。',
    tip: 'look for（探す）と混同しやすい。after は「後を追う」＝世話、for は「求めて」＝探す。',
    example: {
      en: "Could you look after my cat while I'm away?",
      ja: '留守の間、猫の世話をしてもらえますか。',
    },
  },
  {
    id: 'et-495',
    number: 495,
    day: 31,
    en: 'shout at',
    ja: '〜にどなる',
    jaFull: '〜にどなる、〜をどなりつける',
    note: 'shout（叫ぶ）＋ at（一点に向けて）。at が「攻撃的に向ける」感じを出す。',
    tip: 'shout to は「（聞こえるように）大声で呼びかける」で怒っていない。at にした瞬間に怒りが入る。',
    example: {
      en: "Don't shout at the children like that.",
      ja: '子どもたちにそんなふうにどならないで。',
    },
  },
  {
    id: 'et-496',
    number: 496,
    day: 31,
    en: 'take back',
    ja: '〜を返品する',
    jaFull: '（買った商品）を（…に）返品する（to …）',
    note: 'take（持って行く）＋ back（元へ）。買った店へ持って行って戻す。',
    tip: 'bring back（488）と方向が逆で、話し手から離れた場所へ戻すのが take back。「発言を撤回する」の意味も頻出（I take it back.）。',
    example: {
      en: 'I took the shirt back to the shop because it was too small.',
      ja: '小さすぎたのでシャツを店に返品した。',
    },
  },

  // === Day 32 — 動詞句5「動詞＋A＋前置詞＋B」型 ===
  {
    id: 'et-497',
    number: 497,
    day: 32,
    en: 'take A to B',
    ja: 'AをBに連れて行く',
    jaFull: 'AをBに連れて［持って］行く',
    jaAlt: ['AをBに持って行く'],
    note: 'take は「話し手から離れる方向へ持って行く」。B が行き先。',
    tip: 'bring は「話し手のいる方へ持って来る」。相手のいる場所へ向かうときは英語では bring を選ぶことがある（I\'ll bring the wine.）。',
    example: {
      en: "I'll take you to the airport tomorrow.",
      ja: '明日、空港まで送るよ。',
    },
  },
  {
    id: 'et-498',
    number: 498,
    day: 32,
    en: 'help A with B',
    ja: 'AのBを手伝う',
    jaFull: 'A（人）のB（仕事など）を手伝う',
    note: 'A は人、B は仕事。「人を、B の件で助ける」という組み立て。',
    tip: '手伝う中身が動詞なら help A (to) do（532）。名詞なら with、動詞なら (to) do で決まる。',
    example: {
      en: 'Can you help me with the dishes?',
      ja: '皿洗いを手伝ってくれる？',
    },
  },
  {
    id: 'et-499',
    number: 499,
    day: 32,
    en: 'invite A to B',
    ja: 'AをBに招待する',
    jaFull: 'AをBに招待する',
    note: 'invite（招く）＋ to（〜へ）。B は会や場所。',
    tip: 'to の後ろが動詞になると invite A to do（533）で「Aに〜するよう勧める」。同じ形で中身により意味が変わる。',
    example: {
      en: 'They invited us to their wedding.',
      ja: '彼らは私たちを結婚式に招待してくれた。',
    },
  },
  {
    id: 'et-500',
    number: 500,
    day: 32,
    en: 'drive A to B',
    ja: 'AをBまで車で送る',
    jaFull: 'AをBまで車で送る',
    note: 'drive は「（車を）運転する」。A を乗せて B まで運転する。',
    tip: '手段が動詞になるのが英語らしいところ。歩いて送るなら walk A to B、手段を問わないなら take A to B（497）。',
    example: {
      en: 'My father drove me to school this morning.',
      ja: '今朝は父が学校まで車で送ってくれた。',
    },
  },
  {
    id: 'et-501',
    number: 501,
    day: 32,
    en: 'ask A for B',
    ja: 'AにBを求める',
    jaFull: 'AにBを求める',
    note: 'ask（尋ねる）＋ for（求めて）。A が人、B が欲しい物。',
    tip: 'ask A about B は「AにBについて尋ねる」で、求めているのは情報。for は「くれ」、about は「教えて」。',
    example: {
      en: 'She asked her boss for a day off.',
      ja: '彼女は上司に休みを一日求めた。',
    },
  },
  {
    id: 'et-502',
    number: 502,
    day: 32,
    en: 'introduce A to B',
    ja: 'AをBに紹介する',
    jaFull: 'AをBに紹介する',
    note: 'introduce は「中へ導き入れる」。A を B の側へ引き合わせる。',
    tip: '日本語の語順と逆になりやすい。「（相手）に（人）を紹介する」＝ introduce 紹介される人 to 紹介先。',
    example: {
      en: 'Let me introduce my sister to you.',
      ja: '妹をあなたに紹介させてください。',
    },
  },
  {
    id: 'et-503',
    number: 503,
    day: 32,
    en: 'put A in B',
    ja: 'AをBに入れる',
    jaFull: 'AをBに入れる',
    note: 'put（置く）＋ in（中に）。',
    tip: 'in は「中へ」、on は「面の上へ」。外から中への移動を強調したければ put A into B。',
    example: {
      en: 'Put the milk in the fridge, please.',
      ja: '牛乳を冷蔵庫に入れておいて。',
    },
  },
  {
    id: 'et-504',
    number: 504,
    day: 32,
    en: 'spend A on B',
    ja: 'AをBに使う',
    jaFull: 'A（金）をBに使う',
    note: 'spend（費やす）＋ on（〜の上に）。A はお金や時間。',
    tip: '時間の使い道は spend A doing の形が定番（I spent two hours cooking.）。お金は on、行為は doing。',
    example: {
      en: 'We spent 50,000 yen on the trip.',
      ja: '旅行に5万円使った。',
    },
  },
  {
    id: 'et-505',
    number: 505,
    day: 32,
    en: 'show A around B',
    ja: 'AにBを案内する',
    jaFull: 'AにB（場所）を案内する、案内して回る',
    note: 'show（見せる）＋ around（周囲を）。B を一周見せて回る。',
    tip: 'B を省いて show A around だけでも「案内して回る」。名詞の show は「番組・展覧会・ショー」。',
    example: {
      en: 'She showed us around the factory.',
      ja: '彼女は工場を案内してくれた。',
    },
  },
  {
    id: 'et-506',
    number: 506,
    day: 32,
    en: 'show A to B',
    ja: 'AをBに見せる',
    jaFull: 'AをBに見せる',
    note: 'A が見せる物、B が見せる相手。',
    tip: 'show B A（show me the picture）と語順を入れ替えても同じ意味。to があるほうが相手が強調される。',
    example: {
      en: 'Show your ticket to the staff at the gate.',
      ja: '改札で係員に切符を見せてください。',
    },
  },
  {
    id: 'et-507',
    number: 507,
    day: 32,
    en: 'tell A about B',
    ja: 'AにBについて話す',
    jaFull: 'A（人）にBについて話す',
    note: 'tell は「相手」を直接目的語に取る動詞。A は必ず人。',
    tip: 'speak / talk は about の前に to が要る（talk to A about B）。tell に to を付けないのがここの分かれ目。',
    example: {
      en: 'Tell me about your new job.',
      ja: '新しい仕事のことを聞かせて。',
    },
  },
  {
    id: 'et-508',
    number: 508,
    day: 32,
    en: 'share A with B',
    ja: 'AをBと一緒に使う',
    jaFull: 'AをB（人）と一緒に使う、共有する',
    note: 'share（分ける）＋ with（一緒に）。',
    tip: '「共有している」という状態にも使える（We share a room.）。相手は必ず with で示す。',
    example: {
      en: 'I share an apartment with two friends.',
      ja: '友人2人とアパートをシェアしている。',
    },
  },
  {
    id: 'et-509',
    number: 509,
    day: 32,
    en: 'thank A for B',
    ja: 'AにBの礼を言う',
    jaFull: 'AにBの礼を言う',
    note: 'for が「何に対して」を示す。',
    tip: 'for の後ろは名詞か doing。Thank you for coming.（来てくれてありがとう）のように動名詞が来る形が頻出。',
    example: {
      en: 'I thanked her for the birthday present.',
      ja: '誕生日プレゼントのお礼を彼女に言った。',
    },
  },
  {
    id: 'et-510',
    number: 510,
    day: 32,
    en: 'make A into B',
    ja: 'AをBにする',
    jaFull: 'AをBにする、（作り）変える',
    note: 'make（作る）＋ into（別の物へ）。素材 A が姿を変えて B になる。',
    tip: 'make A B（make me happy）と混同しない。into があると「作り変える」。原料側から言うなら B is made from A。',
    example: {
      en: 'They made the old school into a museum.',
      ja: '彼らは古い校舎を博物館に作り変えた。',
    },
  },
  {
    id: 'et-511',
    number: 511,
    day: 32,
    en: 'pay A for B',
    ja: 'AにBの代金を払う',
    jaFull: '❶A（人）にBの代金を払う ❷A（代金）をBに払う',
    note: 'A に人が来るか金額が来るかで役割が入れ替わる、珍しい形。for の後ろが「買った物」なのは共通。',
    tip: 'I paid him for the ticket.（人に払う）と I paid 3,000 yen for the ticket.（金額を払う）を並べて覚えると迷わない。',
    example: {
      en: 'I paid the driver for the ride.',
      ja: '運転手に乗車料金を払った。',
    },
  },
  {
    id: 'et-512',
    number: 512,
    day: 32,
    en: 'exchange A for B',
    ja: 'AをBと交換する',
    jaFull: 'A（物）をB（物）と交換する、取り換える',
    note: 'for が「引き換えに」。手放すのが A、受け取るのが B。',
    tip: 'exchange A with B にすると「B という相手と A をやり取りする」（exchange emails with him）。for は物、with は相手。',
    example: {
      en: 'Can I exchange this shirt for a larger one?',
      ja: 'このシャツを大きいサイズと交換できますか。',
    },
  },

  // === Day 33 — 動詞句6「動詞＋to do［doing］」型 ===
  {
    id: 'et-513',
    number: 513,
    day: 33,
    en: 'go doing',
    ja: '〜しに行く',
    jaFull: '〜しに行く',
    note: 'go swimming / go shopping。行った先での活動を doing で表す。',
    tip: 'go to swim とは言わない。場所を足すときも to ではなく at / in（go shopping at the mall）。',
    example: {
      en: 'We went fishing in the river last Sunday.',
      ja: '先週の日曜、川へ釣りに行った。',
    },
  },
  {
    id: 'et-514',
    number: 514,
    day: 33,
    en: 'need to do',
    ja: '〜する必要がある',
    jaFull: '〜する必要がある、〜しなければならない',
    note: 'need はここでは一般動詞。否定・疑問は do / does / did で作る。',
    tip: "don't need to do は「する必要がない」。must not（してはいけない）とは意味がまるで違うので、否定形で取り違えないこと。",
    example: {
      en: 'You need to book the ticket in advance.',
      ja: 'チケットは事前に予約する必要がある。',
    },
  },
  {
    id: 'et-515',
    number: 515,
    day: 33,
    en: 'decide to do',
    ja: '〜しようと決心する',
    jaFull: '〜しようと決心する、〜することに決める',
    note: 'decide は to do を取る。doing は取らない。',
    tip: '「〜しないと決める」は decide not to do で、not は to の前。名詞は decision（make a decision）。',
    example: {
      en: 'She decided to study abroad next year.',
      ja: '彼女は来年留学することに決めた。',
    },
  },
  {
    id: 'et-516',
    number: 516,
    day: 33,
    en: 'forget to do',
    ja: '〜するのを忘れる',
    jaFull: '〜するのを忘れる',
    note: 'これからやることを忘れる——つまり、まだやっていない。',
    tip: 'forget doing は「〜したことを忘れる」で、もう済んでいる。remember も同じ対立を持つ。時間の向きが逆になる。',
    example: {
      en: "Don't forget to lock the door.",
      ja: 'ドアの鍵を閉めるのを忘れないで。',
    },
  },
  {
    id: 'et-517',
    number: 517,
    day: 33,
    en: 'enjoy doing',
    ja: '〜して楽しむ',
    jaFull: '〜して楽しむ',
    note: 'enjoy は to do を取らない代表格。必ず doing。',
    tip: 'enjoy to do は誤り。enjoy oneself で「楽しむ」（Did you enjoy yourself?）。',
    example: {
      en: 'I enjoy listening to music before bed.',
      ja: '寝る前に音楽を聴くのが楽しい。',
    },
  },
  {
    id: 'et-518',
    number: 518,
    day: 33,
    en: 'would like to do',
    ja: '〜したい',
    jaFull: '〜したい（のですが）',
    note: 'want to do の丁寧版。控えめに希望を伝える。',
    tip: "would は 'd に短縮されることが多い（I'd like to ...）。疑問形 Would you like to ...? は誘いの定型。",
    example: {
      en: "I'd like to reserve a table for two.",
      ja: '2名で席を予約したいのですが。',
    },
    synonymIds: ['et-523'],
  },
  {
    id: 'et-519',
    number: 519,
    day: 33,
    en: 'love doing',
    ja: '〜するのが大好きである',
    jaFull: '〜するのが大好きである（love to do も可）',
    note: 'like より強い。活動そのものを楽しんでいるときは doing が自然。',
    tip: 'love to do も使える。英では「その活動が楽しい」＝ doing、「そうするのがよいと思ってそうしている（方針・習慣）」＝ to do の傾向。米語では to do も広く使われるので、どちらでも誤りにはならない。',
    example: {
      en: 'She loves cooking for her family.',
      ja: '彼女は家族に料理を作るのが大好きだ。',
    },
  },
  {
    id: 'et-520',
    number: 520,
    day: 33,
    en: 'plan to do',
    ja: '〜するつもりである',
    jaFull: '〜するつもり［予定］である',
    jaAlt: ['〜する予定である'],
    note: 'plan は to do を取る。',
    tip: '名詞の plan は for 〜 と to do の両方を取る（a plan for the trip / a plan to move）。',
    example: {
      en: 'We plan to move to Osaka in April.',
      ja: '4月に大阪へ引っ越す予定だ。',
    },
  },
  {
    id: 'et-521',
    number: 521,
    day: 33,
    en: 'start doing',
    ja: '〜し始める',
    jaFull: '〜し始める（≒ begin doing［to do］）',
    note: 'start は doing も to do も取れる（begin / continue / like なども同じ）。',
    tip: '進行形のときは to do を選ぶ。It\'s starting to rain. のほうが -ing が続かず読みやすい。',
    example: {
      en: 'He started learning Spanish last month.',
      ja: '彼は先月スペイン語を習い始めた。',
    },
  },
  {
    id: 'et-522',
    number: 522,
    day: 33,
    en: 'finish doing',
    ja: '〜し終える',
    jaFull: '〜し終える',
    note: 'finish は doing のみ。to do は取らない。',
    tip: 'enjoy / finish / keep / stop は目的語に doing しか取らない。stop to do の to do は目的語ではなく「〜するために」の副詞句なので別物（524）。',
    example: {
      en: 'Have you finished writing the report?',
      ja: '報告書は書き終わった？',
    },
  },
  {
    id: 'et-523',
    number: 523,
    day: 33,
    en: 'hope to do',
    ja: '〜したいと思う',
    jaFull: '〜したいと思う、〜することを望む',
    note: '実現しそうな望みに使う。',
    tip: 'hope A to do とは言えない。「Aに〜してほしい」は want A to do（530）か hope (that) A will do。',
    example: {
      en: 'I hope to see you again soon.',
      ja: 'また近いうちにお会いしたいです。',
    },
    synonymIds: ['et-518'],
  },
  {
    id: 'et-524',
    number: 524,
    day: 33,
    en: 'stop doing',
    ja: '〜するのをやめる',
    jaFull: '〜するのをやめる',
    note: 'doing がやめる中身。',
    tip: 'stop to do は「〜するために立ち止まる」で全く別。He stopped smoking（禁煙した）と He stopped to smoke（吸うために立ち止まった）を並べて確認しておくこと。',
    example: {
      en: 'You should stop eating so much sugar.',
      ja: 'そんなに砂糖を摂るのはやめたほうがいい。',
    },
  },
  {
    id: 'et-525',
    number: 525,
    day: 33,
    en: 'try to do',
    ja: '〜しようとする',
    jaFull: '〜しようとする、試みる、努力する',
    note: '努力する、という意味。できたかどうかまでは言っていない。',
    tip: 'try doing は「試しに〜してみる」で、できる前提の話（Try turning it off.）。',
    example: {
      en: 'I tried to open the window, but it was stuck.',
      ja: '窓を開けようとしたが、動かなかった。',
    },
  },
  {
    id: 'et-526',
    number: 526,
    day: 33,
    en: "can't wait to do",
    ja: '〜するのが待ちきれない',
    jaFull: '〜するのが待ちきれない',
    note: '直訳は「〜するのを待てない」。楽しみでたまらない、という定型。',
    tip: '後ろが名詞なら can\'t wait for（I can\'t wait for summer.）。動詞なら to do、名詞なら for。',
    example: {
      en: "I can't wait to see you again.",
      ja: 'また会えるのが待ちきれない。',
    },
  },
  {
    id: 'et-527',
    number: 527,
    day: 33,
    en: 'learn to do',
    ja: '〜できるようになる',
    jaFull: '〜できるようになる、〜することを覚える',
    note: '習得の結果として「できるようになる」。',
    tip: 'learn doing とは言わない。learn about 〜 は「〜について知識を得る」で、できるようになる話ではない。',
    example: {
      en: 'She learned to swim when she was five.',
      ja: '彼女は5歳で泳げるようになった。',
    },
  },
  {
    id: 'et-528',
    number: 528,
    day: 33,
    en: 'keep doing',
    ja: '〜し続ける',
    jaFull: '〜し続ける',
    note: 'keep は doing のみ。',
    tip: 'keep on doing も同義で、しつこさが強調される。keep A doing なら「Aを〜させ続ける」（Sorry to keep you waiting.）。',
    example: {
      en: 'He kept talking for an hour.',
      ja: '彼は1時間しゃべり続けた。',
    },
  },

  // === Day 34 — 動詞句7「動詞＋A＋to do」「be動詞＋形容詞＋to do」型 ===
  {
    id: 'et-529',
    number: 529,
    day: 34,
    en: 'ask A to do',
    ja: 'Aに〜するように頼む',
    jaFull: 'Aに〜するように頼む',
    note: 'ask（頼む）＋ A（人）＋ to do（頼む中身）。',
    tip: '「〜しないよう頼む」は ask A not to do。ask A for B（501）は名詞を求める形で、to do とは別。',
    example: {
      en: 'I asked him to close the window.',
      ja: '窓を閉めてくれるよう彼に頼んだ。',
    },
  },
  {
    id: 'et-530',
    number: 530,
    day: 34,
    en: 'want A to do',
    ja: 'Aに〜してほしいと思っている',
    jaFull: 'Aに〜してほしいと思っている',
    note: 'want の目的語が「A が〜すること」全体。',
    tip: 'want that ... とは言えない。日本語の「〜してほしい」はほぼこの形で表す。',
    example: {
      en: 'My parents want me to become a teacher.',
      ja: '両親は私に教師になってほしいと思っている。',
    },
    synonymIds: ['et-535'],
  },
  {
    id: 'et-531',
    number: 531,
    day: 34,
    en: 'tell A to do',
    ja: 'Aに〜するように言う',
    jaFull: 'Aに〜するように言う',
    note: '指示・命令に近い言い方。',
    tip: 'say はこの形を取れない（say me to do は誤り）。人に何かさせるなら tell。',
    example: {
      en: 'The teacher told us to be quiet.',
      ja: '先生は私たちに静かにするよう言った。',
    },
  },
  {
    id: 'et-532',
    number: 532,
    day: 34,
    en: 'help A (to) do',
    ja: 'Aが〜するのを手伝う',
    jaFull: 'Aが〜するのを手伝う',
    note: 'help は to を省ける数少ない動詞。口語では省くほうが普通。',
    tip: '手伝う中身が名詞なら help A with B（498）。動詞か名詞かで形が決まる。',
    example: {
      en: 'Can you help me carry this box?',
      ja: 'この箱を運ぶのを手伝ってくれる？',
    },
  },
  {
    id: 'et-533',
    number: 533,
    day: 34,
    en: 'invite A to do',
    ja: 'Aに〜するよう求める',
    jaFull: 'Aに〜するよう求める、勧める',
    note: 'to の後ろが動詞。招待というより「〜しませんかと誘う」。',
    tip: 'invite A to B（499）は to の後ろが名詞（場所・会）。同じ invite ... to でも後ろの品詞で意味が変わる。',
    example: {
      en: 'They invited me to join the team.',
      ja: '彼らは私にチームに入るよう誘ってくれた。',
    },
  },
  {
    id: 'et-534',
    number: 534,
    day: 34,
    en: 'teach A to do',
    ja: 'Aに〜のやり方を教える',
    jaFull: 'Aに〜のやり方を教える',
    note: 'teach（教える）＋ A（人）＋ to do（できるようにする中身）。',
    tip: 'teach A B（teach me English）は知識を教える形。to do は「できるようにする」ほうを指す。',
    example: {
      en: 'My grandfather taught me to ride a bike.',
      ja: '祖父が自転車の乗り方を教えてくれた。',
    },
  },
  {
    id: 'et-535',
    number: 535,
    day: 34,
    en: 'would like A to do',
    ja: 'Aに〜してもらいたいと思っている',
    jaFull: 'Aに〜してもらいたいと思っている',
    note: 'want A to do（530）の丁寧版。',
    tip: "would は 'd に短縮される。I'd like you to meet my wife.（妻を紹介させてください）は定型表現。",
    example: {
      en: "I'd like you to check this document.",
      ja: 'この書類を確認していただきたいのですが。',
    },
    synonymIds: ['et-530'],
  },
  {
    id: 'et-536',
    number: 536,
    day: 34,
    en: 'wait for A to do',
    ja: 'Aが〜するのを待つ',
    jaFull: 'Aが〜するのを待つ',
    note: 'wait for（待つ）＋ A ＋ to do。A が to do の意味上の主語になる。',
    tip: 'for を落とさないこと。wait A to do は誤り。「〜を待つ」だけなら wait for A。',
    example: {
      en: 'We waited for the rain to stop.',
      ja: '雨がやむのを待った。',
    },
  },
  {
    id: 'et-537',
    number: 537,
    day: 34,
    en: 'be able to do',
    ja: '〜することができる',
    jaFull: '〜することができる',
    note: 'can とほぼ同義だが、時制を自由に作れるのが強み。',
    tip: 'will be able to / have been able to のように、can が置けない位置で活躍する。過去の一回きりの成功は was able to（could だと不自然）。',
    example: {
      en: 'I will be able to finish it by Friday.',
      ja: '金曜までには終えられるでしょう。',
    },
  },
  {
    id: 'et-538',
    number: 538,
    day: 34,
    en: 'be ready to do',
    ja: '〜する準備ができている',
    jaFull: '〜する準備［用意］ができている',
    jaAlt: ['〜する用意ができている'],
    note: 'ready（用意ができた）＋ to do。',
    tip: '後ろが名詞なら be ready for（554）。to do か for かは後ろの品詞で決まる。',
    example: {
      en: 'Are you ready to order?',
      ja: 'ご注文はお決まりですか。',
    },
  },
  {
    id: 'et-539',
    number: 539,
    day: 34,
    en: 'be surprised to do',
    ja: '〜して驚く',
    jaFull: '〜して驚く',
    note: 'to do が驚いた理由。感情の原因を表す不定詞。',
    tip: 'be surprised at ＋ 名詞 の形もある。人が主語なら surprised（驚かされた側）、物なら surprising。',
    example: {
      en: 'I was surprised to hear the news.',
      ja: 'その知らせを聞いて驚いた。',
    },
  },
  {
    id: 'et-540',
    number: 540,
    day: 34,
    en: 'be sorry to do',
    ja: '〜して気の毒に思う',
    jaFull: '〜して気の毒［残念］に思う',
    jaAlt: ['〜して残念に思う'],
    note: 'sorry は「すまない」だけでなく「気の毒だ・残念だ」。',
    tip: "I'm sorry to hear that. は相手の不幸への定番の応答で、謝罪ではない。",
    example: {
      en: "I'm sorry to hear about your father.",
      ja: 'お父様のこと、お気の毒です。',
    },
  },
  {
    id: 'et-541',
    number: 541,
    day: 34,
    en: 'be glad to do',
    ja: '〜してうれしい',
    jaFull: '〜してうれしい（≒ be happy to do）',
    note: 'glad は「うれしい」。to do がその理由。',
    tip: "依頼への返事 I'd be glad to.（喜んで）でも使う。be happy to do とほぼ交換可能。",
    example: {
      en: "I'm glad to see you again.",
      ja: 'また会えてうれしいです。',
    },
    synonymIds: ['et-542'],
  },
  {
    id: 'et-542',
    number: 542,
    day: 34,
    en: 'be happy to do',
    ja: '〜してうれしい',
    jaFull: '〜してうれしい（≒ be glad to do）',
    note: '541 と同義。感情の原因を to do で示す形。',
    tip: "「喜んで〜する」という申し出にもなる（I'd be happy to help.）。",
    example: {
      en: "We're happy to have you on the team.",
      ja: 'チームに加わってくれてうれしいです。',
    },
    synonymIds: ['et-541'],
  },
  {
    id: 'et-543',
    number: 543,
    day: 34,
    en: 'be sure to do',
    ja: '必ず〜する',
    jaFull: '必ず［ちゃんと］〜する',
    jaAlt: ['ちゃんと〜する'],
    note: '話し手から見て「間違いなくそうなる」。',
    tip: '命令文だと「必ず〜してね」（Be sure to lock the door.）。be sure of / about ＋ 名詞 は「〜を確信している」で別物。',
    example: {
      en: 'Be sure to take your umbrella.',
      ja: '必ず傘を持って行ってね。',
    },
  },
  {
    id: 'et-544',
    number: 544,
    day: 34,
    en: 'be about to do',
    ja: '〜しようとしている',
    jaFull: '（まさに）〜しようとしている',
    note: 'about が「すぐそば」。動作の直前を指す。',
    tip: '「今まさに」なので、tomorrow のような先の時を表す語句とは相性が悪い。そこは will を使う。',
    example: {
      en: 'The train is about to leave.',
      ja: '電車はまさに出発しようとしている。',
    },
  },

  // === Day 35 — 動詞句8「be動詞＋形容詞＋前置詞」型 ===
  {
    id: 'et-545',
    number: 545,
    day: 35,
    en: 'be late for',
    ja: '〜に遅刻する',
    jaFull: '〜に遅刻する、遅れる',
    note: 'late（遅い）＋ for（〜に対して）。',
    tip: '「10分遅刻する」は be ten minutes late for 〜。数量は late の前に置く。',
    example: {
      en: "Don't be late for the meeting.",
      ja: '会議に遅刻しないように。',
    },
  },
  {
    id: 'et-546',
    number: 546,
    day: 35,
    en: 'be good at',
    ja: '〜が得意である',
    jaFull: '〜が得意［上手］である',
    jaAlt: ['〜が上手である'],
    note: 'at が「一点」を指し、その分野で良い、という組み立て。',
    tip: 'at の後ろは名詞か doing（good at cooking）。反対は be bad［poor］at。',
    example: {
      en: 'She is good at explaining difficult things.',
      ja: '彼女は難しいことを説明するのが得意だ。',
    },
  },
  {
    id: 'et-547',
    number: 547,
    day: 35,
    en: 'be far from',
    ja: '〜から遠い',
    jaFull: '〜から遠い',
    note: '距離の far。',
    tip: '比喩でも頻出で、far from perfect は「完璧には程遠い」。距離だけの表現だと思っていると読み違える。',
    example: {
      en: 'My house is far from the station.',
      ja: '家は駅から遠い。',
    },
  },
  {
    id: 'et-548',
    number: 548,
    day: 35,
    en: 'be different from',
    ja: '〜と異なる',
    jaFull: '〜と異なる、違う',
    note: 'different（異なる）＋ from（〜から離れて）。',
    tip: '米口語では different than も使われる。名詞は difference（the difference between A and B）。',
    example: {
      en: 'British English is a little different from American English.',
      ja: 'イギリス英語はアメリカ英語と少し異なる。',
    },
  },
  {
    id: 'et-549',
    number: 549,
    day: 35,
    en: 'be interested in',
    ja: '〜に興味を持っている',
    jaFull: '〜に興味を持っている、関心がある',
    note: '人は「興味を持たされている」側なので過去分詞。in の後ろは名詞か doing。',
    tip: "interesting は「（物が）面白い」。I am interesting. と言うと「私は面白い人間だ」になってしまう。",
    example: {
      en: "I'm interested in learning about other cultures.",
      ja: '他の文化について学ぶことに興味がある。',
    },
  },
  {
    id: 'et-550',
    number: 550,
    day: 35,
    en: 'be proud of',
    ja: '〜を誇りに思っている',
    jaFull: '〜を誇りに思っている、誇りとしている',
    note: 'proud（誇らしい）＋ of（〜について）。',
    tip: "be proud to do の形もある（I'm proud to be here.）。名詞は pride。",
    example: {
      en: "I'm proud of what you've done.",
      ja: 'あなたのしたことを誇りに思う。',
    },
  },
  {
    id: 'et-551',
    number: 551,
    day: 35,
    en: 'be worried about',
    ja: '〜のことで心配している',
    jaFull: '〜のことで心配している',
    note: 'worry は他動詞「心配させる」なので、人は worried（心配させられた）になる。',
    tip: "worry about 〜 と動詞で言っても同じ。Don't worry about it. が最頻出。",
    example: {
      en: "She is worried about her son's health.",
      ja: '彼女は息子の健康を心配している。',
    },
  },
  {
    id: 'et-552',
    number: 552,
    day: 35,
    en: 'be covered with',
    ja: '〜で覆われている',
    jaFull: '〜で覆われている',
    note: 'cover（覆う）の受動態。with が「覆っている物」。',
    tip: 'be covered in も同じくらい使われる。雪や埃のように全面を覆う場合は in が自然なことも多い。',
    example: {
      en: 'The mountain was covered with snow.',
      ja: '山は雪で覆われていた。',
    },
  },
  {
    id: 'et-553',
    number: 553,
    day: 35,
    en: 'be full of',
    ja: '〜でいっぱいである',
    jaFull: '〜でいっぱいである（≒ be filled with）',
    note: 'full（満ちた）＋ of（中身）。',
    tip: 'be filled with（560）と同義。full は状態を表す形容詞、filled は fill の受動態、という成り立ちの違いだけ。',
    example: {
      en: 'The room was full of people.',
      ja: '部屋は人でいっぱいだった。',
    },
    synonymIds: ['et-560'],
  },
  {
    id: 'et-554',
    number: 554,
    day: 35,
    en: 'be ready for',
    ja: '〜の準備ができている',
    jaFull: '〜の準備［用意］ができている',
    jaAlt: ['〜の用意ができている'],
    note: '後ろが名詞のときは for。',
    tip: '動詞が続くなら be ready to do（538）。for か to do かは後ろの品詞で決まる。',
    example: {
      en: 'Are you ready for the exam?',
      ja: '試験の準備はできている？',
    },
  },
  {
    id: 'et-555',
    number: 555,
    day: 35,
    en: 'be made of',
    ja: '〜で作られている',
    jaFull: '〜で作られている（見た目で材料が分かる場合）',
    note: '材料が見た目で分かるときの of。',
    tip: '見て分からないほど変化しているなら be made from（Wine is made from grapes.）。製造地なら be made in。',
    example: {
      en: 'This desk is made of wood.',
      ja: 'この机は木でできている。',
    },
  },
  {
    id: 'et-556',
    number: 556,
    day: 35,
    en: 'be absent from',
    ja: '〜を欠席している',
    jaFull: '〜を欠席［欠勤］している',
    jaAlt: ['〜を欠勤している'],
    note: 'absent（不在の）＋ from（〜から離れて）。',
    tip: '反対は be present at。口語で「休む」は take a day off。',
    example: {
      en: 'He was absent from school yesterday.',
      ja: '彼は昨日学校を欠席した。',
    },
  },
  {
    id: 'et-557',
    number: 557,
    day: 35,
    en: 'be scared of',
    ja: '〜を怖がる',
    jaFull: '〜を怖がる（≒ be afraid of）',
    note: 'scare（怖がらせる）の受動態。',
    tip: 'be afraid of（559）とほぼ同義。scared のほうが口語的で、その場の恐怖に使いやすい。',
    example: {
      en: 'My little brother is scared of the dark.',
      ja: '弟は暗闇を怖がる。',
    },
    synonymIds: ['et-559'],
  },
  {
    id: 'et-558',
    number: 558,
    day: 35,
    en: 'be tired of',
    ja: '〜に飽きている',
    jaFull: '〜に飽きている、うんざりしている',
    note: 'of は「〜について」。',
    tip: 'be tired from は「〜で疲れている」（肉体的）。of と from で意味が変わるので、前置詞まで込みで覚えること。',
    example: {
      en: "I'm tired of eating the same lunch every day.",
      ja: '毎日同じ昼食を食べるのに飽きている。',
    },
  },
  {
    id: 'et-559',
    number: 559,
    day: 35,
    en: 'be afraid of',
    ja: '〜を怖がる',
    jaFull: '〜を怖がる、恐れる（≒ be scared of）',
    note: 'afraid（恐れて）＋ of（対象）。',
    tip: "I'm afraid ... で「残念ながら〜」と切り出す用法も頻出。be afraid to do なら「怖くて〜できない」。",
    example: {
      en: 'Many people are afraid of making mistakes.',
      ja: '多くの人は失敗を恐れる。',
    },
    synonymIds: ['et-557'],
  },
  {
    id: 'et-560',
    number: 560,
    day: 35,
    en: 'be filled with',
    ja: '〜でいっぱいである',
    jaFull: '〜でいっぱいである（≒ be full of）',
    note: 'fill（満たす）の受動態。何で満たされたかを with が示す。',
    tip: 'fill A with B（AをBで満たす）の受動形だと分かると、with がここにある理由が腑に落ちる。',
    example: {
      en: 'Her eyes were filled with tears.',
      ja: '彼女の目は涙でいっぱいだった。',
    },
    synonymIds: ['et-553'],
  },
];
