import { describe, it, expect } from 'vitest';
import {
  coerceFieldDefs,
  coerceFieldValues,
  formatFieldValue,
  hasNoErrors,
  MAX_ASSET_FIELDS,
  MAX_FIELD_TEXT_LENGTH,
  nextFieldKey,
  normalizeFieldDefs,
  validateFieldDefs,
  validateFieldValues,
  type AssetFieldDef,
} from './asset-fields';

const def = (overrides: Partial<AssetFieldDef> = {}): AssetFieldDef => ({
  key: 'f1',
  label: '銘柄',
  type: 'text',
  required: false,
  unit: null,
  ...overrides,
});

describe('nextFieldKey', () => {
  it('starts at f1 for an empty list', () => {
    expect(nextFieldKey([])).toBe('f1');
  });

  it('fills the first gap rather than continuing past the end', () => {
    // Keys are an identity, not an ordering. Recycling a retired key is only
    // safe because removing a definition also removes its values from every
    // holding of that category -- see reshapeHoldings in
    // server/repositories/asset-category.repository.ts and its regression test.
    // Without that, this line would make a deleted value reappear under the
    // next parameter to take the key.
    expect(nextFieldKey([def({ key: 'f1' }), def({ key: 'f3' })])).toBe('f2');
  });

  it('never returns a key already in use', () => {
    const defs = Array.from({ length: 5 }, (_, i) => def({ key: `f${i + 1}` }));
    expect(defs.map((d) => d.key)).not.toContain(nextFieldKey(defs));
  });
});

describe('validateFieldDefs', () => {
  it('accepts a well-formed list', () => {
    expect(hasNoErrors(validateFieldDefs([def(), def({ key: 'f2', label: '数量', type: 'number' })]).errors)).toBe(true);
  });

  it('rejects an empty label', () => {
    expect(validateFieldDefs([def({ label: '   ' })]).errors.f1).toBeDefined();
  });

  it('rejects duplicate keys', () => {
    // Two definitions sharing a key means one stored value serves both, and
    // editing either silently overwrites the other.
    expect(validateFieldDefs([def(), def({ label: '別名' })]).errors._).toBeDefined();
  });

  it('rejects a list longer than the cap', () => {
    const defs = Array.from({ length: MAX_ASSET_FIELDS + 1 }, (_, i) => def({ key: `f${i + 1}` }));
    expect(validateFieldDefs(defs).errors._).toBeDefined();
  });

  it('rejects a key that was not generated by nextFieldKey', () => {
    expect(validateFieldDefs([def({ key: 'drop table' })]).errors._).toBeDefined();
  });

  it('keeps the FIRST list-level problem rather than the last', () => {
    // '_' is a single slot. Letting a later problem overwrite would replace
    // 'too many parameters' with a message about a key the user cannot see.
    const defs = [
      ...Array.from({ length: MAX_ASSET_FIELDS + 1 }, (_, i) => def({ key: `f${i + 1}` })),
      def({ key: 'f1' }),
    ];
    expect(validateFieldDefs(defs).errors._).toContain(String(MAX_ASSET_FIELDS));
  });
});

describe('normalizeFieldDefs', () => {
  it('trims the label and turns a blank unit into null', () => {
    // The dialog trims too, but the dialog is not what the server receives.
    expect(normalizeFieldDefs([def({ label: '  銘柄  ', unit: '  ' })])).toEqual([
      def({ label: '銘柄', unit: null }),
    ]);
  });

  it('defaults a missing required flag to false', () => {
    const [normalized] = normalizeFieldDefs([
      { key: 'f1', label: 'x', type: 'text', unit: null } as never,
    ]);
    expect(normalized.required).toBe(false);
  });
});

describe('validateFieldValues', () => {
  it('stores a number field as a number even when the form sent a string', () => {
    // <input> only ever produces strings; without the coercion a ledger would
    // accumulate a mix of 1200 and '1200' that every later sum must defend against.
    const { values, errors } = validateFieldValues([def({ type: 'number' })], { f1: '1200' });
    expect(errors).toEqual({});
    expect(values.f1).toBe(1200);
  });

  it('treats an empty string as "not filled in" rather than zero', () => {
    // Number('') is 0. Storing that would turn a blank box into a real figure.
    const { values } = validateFieldValues([def({ type: 'number' })], { f1: '' });
    expect(values.f1).toBeNull();
  });

  it('reports a required field left blank', () => {
    const { errors } = validateFieldValues([def({ required: true })], {});
    expect(errors.f1).toContain('必須');
  });

  it('reports a number field that is not a number', () => {
    const { errors } = validateFieldValues([def({ type: 'number' })], { f1: 'たくさん' });
    expect(errors.f1).toBeDefined();
  });

  it('reports a date that is not yyyy-MM-dd', () => {
    expect(validateFieldValues([def({ type: 'date' })], { f1: '2026/01/01' }).errors.f1).toBeDefined();
    expect(validateFieldValues([def({ type: 'date' })], { f1: '2026-01-01' }).errors.f1).toBeUndefined();
  });

  it('drops keys the category no longer defines instead of failing', () => {
    // A field removed while someone had the form open must not make their save
    // fail; the value simply stops meaning anything.
    const { values, errors } = validateFieldValues([def()], { f1: 'A', f9: '取り残し' });
    expect(errors).toEqual({});
    expect(values).toEqual({ f1: 'A' });
  });

  it('trims text and caps its length', () => {
    const long = 'あ'.repeat(MAX_FIELD_TEXT_LENGTH + 10);
    const { values, errors } = validateFieldValues([def()], { f1: `  ${long}  ` });
    expect(errors.f1).toBeDefined();
    expect(String(values.f1)).toHaveLength(MAX_FIELD_TEXT_LENGTH);
  });

  it('produces a value for every definition, so a holding is never partially shaped', () => {
    const { values } = validateFieldValues([def(), def({ key: 'f2' })], {});
    expect(Object.keys(values).sort()).toEqual(['f1', 'f2']);
  });
});

describe('coerceFieldDefs', () => {
  it('drops entries that are not field definitions', () => {
    // Guards the read path: a row written by an older version or edited by hand
    // must not reach the UI as a shape it will crash on.
    expect(coerceFieldDefs([def(), null, { key: 'f2' }, 'nope'])).toEqual([def()]);
  });

  it('returns an empty list for anything that is not an array', () => {
    expect(coerceFieldDefs({ f1: 'x' })).toEqual([]);
    expect(coerceFieldDefs(null)).toEqual([]);
  });

  it('defaults a missing required flag to false and an empty unit to null', () => {
    const [coerced] = coerceFieldDefs([{ key: 'f1', label: '銘柄', type: 'text', unit: '' }]);
    expect(coerced).toEqual(def());
  });
});

describe('coerceFieldValues', () => {
  it('keeps strings, numbers and nulls', () => {
    expect(coerceFieldValues({ f1: 'A', f2: 3, f3: null })).toEqual({ f1: 'A', f2: 3, f3: null });
  });

  it('drops values with no renderer', () => {
    expect(coerceFieldValues({ f1: { nested: true }, f2: true })).toEqual({});
  });

  it('returns an empty object for an array or a non-object', () => {
    expect(coerceFieldValues([1, 2])).toEqual({});
    expect(coerceFieldValues('x')).toEqual({});
  });
});

describe('formatFieldValue', () => {
  it('appends the unit', () => {
    expect(formatFieldValue(def({ type: 'number', unit: '株' }), 1200)).toBe('1,200 株');
  });

  it('shows a dash for a value that was never filled in', () => {
    expect(formatFieldValue(def(), null)).toBe('—');
  });

  it('leaves text alone when there is no unit', () => {
    expect(formatFieldValue(def(), 'eMAXIS Slim')).toBe('eMAXIS Slim');
  });

  it('shows a value the type cannot hold as it is, never as NaN', () => {
    // Holdings are reshaped whenever a definition changes, so this is the belt
    // to that braces -- a row written before that existed, or edited by hand.
    expect(formatFieldValue(def({ type: 'number' }), 'SBI証券')).toBe('SBI証券');
  });
});
