// ---------------------------------------------------------------------------
// The parameter schema an asset category carries, and the one validator that
// checks a holding's values against it.
//
// WHY THIS IS SHARED
//   The same rules have to hold in two places: the form must tell the user which
//   box is wrong before they submit, and the server must refuse a body that
//   never went through that form. Writing them twice guarantees they drift, and
//   the drift is silent -- the UI accepts something the server rejects, or worse
//   the other way round. So the rules live here, in a module with no node and no
//   react imports, and BOTH sides call the same function.
//
// WHY VALUES ARE VALIDATED AT ALL, GIVEN THEY LAND IN JSONB
//   JSONB will store literally anything. Without this, a stale form (a field
//   deleted from the category since the page loaded) would quietly persist keys
//   nothing renders, and a number field would accumulate a mix of 1200 and
//   '1200' that every later sum has to defend against.
// ---------------------------------------------------------------------------

/**
 * What kind of value a parameter holds.
 *
 * Deliberately three, not a general JSON schema. Every extra type is a form
 * control, a validation branch and a display branch; these three cover 銘柄
 * (text), 保有数量 / 取得単価 (number) and 満期日 (date), which is what a
 * household actually records.
 */
export type AssetFieldType = 'text' | 'number' | 'date';

export interface AssetFieldDef {
  /**
   * Stable machine key. NEVER derived from the label.
   *
   * Labels are Japanese and mutable ('銘柄' becomes '銘柄名'); a derived key
   * would either be unrepresentable or would change under a rename and orphan
   * every value already stored. Keys are generated by nextFieldKey() and never
   * change once assigned, so renaming a label keeps the data attached to it.
   */
  key: string;
  /** What the user sees: 銘柄, 保有数量, ... */
  label: string;
  type: AssetFieldType;
  /** A required field blocks saving the holding until it has a value. */
  required: boolean;
  /** Shown after the input (株, 円). Display only -- never used in arithmetic. */
  unit: string | null;
}

/** A single parameter value. null means "not filled in". */
export type AssetFieldValue = string | number | null;

/** One holding's parameters, keyed by AssetFieldDef.key. */
export type AssetFieldValues = Record<string, AssetFieldValue>;

/**
 * Caps, enforced on both sides.
 *
 * These are not arbitrary tidiness: `fields` is JSONB inside a row that the
 * whole 資産 view loads at once, and nothing else bounds how much a client can
 * push into it.
 */
export const MAX_ASSET_FIELDS = 12;
export const MAX_FIELD_LABEL_LENGTH = 24;
export const MAX_FIELD_UNIT_LENGTH = 8;
export const MAX_FIELD_TEXT_LENGTH = 200;

/** Machine keys are generated, so this is a shape assertion, not a UX rule. */
export const FIELD_KEY_PATTERN = /^f[1-9][0-9]{0,3}$/;

const ISO_DATE_PATTERN = /^\d{4}-\d{2}-\d{2}$/;

/**
 * The next unused machine key for a definition list.
 *
 * Deterministic (f1, f2, f3...) rather than random or time-based, so the same
 * edits produce the same keys and the templates in asset-templates.ts can be
 * written out by hand.
 */
export function nextFieldKey(defs: readonly AssetFieldDef[]): string {
  const used = new Set(defs.map((d) => d.key));
  for (let n = 1; n <= MAX_ASSET_FIELDS + defs.length + 1; n += 1) {
    const key = `f${n}`;
    if (!used.has(key)) return key;
  }
  // Unreachable while defs stay under MAX_ASSET_FIELDS, which the validator
  // enforces -- but a silent duplicate key would overwrite a stored value.
  throw new Error('nextFieldKey: no key available');
}

export interface FieldDefValidation {
  /** Empty when the definitions are usable. Keyed by field key, plus '_' for list-level problems. */
  errors: Record<string, string>;
}

/**
 * Checks a category's field DEFINITIONS (the shape), not a holding's values.
 *
 * Runs on the server too: the definitions arrive from the client as JSON and
 * land in JSONB, which validates nothing on its own.
 */
export function validateFieldDefs(defs: readonly AssetFieldDef[]): FieldDefValidation {
  const errors: Record<string, string> = {};

  // List-level problems all share the '_' slot, so the FIRST one wins. Letting a
  // later one overwrite would replace 'too many parameters' with a message about
  // a key the user never typed and cannot see.
  const listError = (message: string): void => {
    if (errors._ === undefined) errors._ = message;
  };

  if (defs.length > MAX_ASSET_FIELDS) {
    listError(`パラメータは ${MAX_ASSET_FIELDS} 個までです`);
  }

  const seen = new Set<string>();
  for (const def of defs) {
    if (!FIELD_KEY_PATTERN.test(def.key)) {
      listError('パラメータの識別子が不正です');
      continue;
    }
    if (seen.has(def.key)) {
      // Two definitions sharing a key means one holding value serves both, and
      // editing either overwrites the other.
      listError('パラメータの識別子が重複しています');
      continue;
    }
    seen.add(def.key);

    const label = def.label.trim();
    if (label.length === 0) {
      errors[def.key] = 'パラメータ名は必須です';
    } else if (label.length > MAX_FIELD_LABEL_LENGTH) {
      errors[def.key] = `パラメータ名は ${MAX_FIELD_LABEL_LENGTH} 文字までです`;
    } else if (def.unit !== null && def.unit.length > MAX_FIELD_UNIT_LENGTH) {
      errors[def.key] = `単位は ${MAX_FIELD_UNIT_LENGTH} 文字までです`;
    }
  }

  return { errors };
}

/**
 * The form a definition list is STORED in.
 *
 * Trimming happens here rather than while the user types (which would make a
 * space impossible to enter mid-label) and rather than only in the dialog
 * (which would leave the HTTP API able to store untrimmed labels). An empty
 * unit becomes null so rendering never appends a stray space.
 */
export function normalizeFieldDefs(defs: readonly AssetFieldDef[]): AssetFieldDef[] {
  return defs.map((def) => ({
    key: def.key,
    label: def.label.trim(),
    type: def.type,
    required: def.required === true,
    unit: def.unit !== null && def.unit.trim() !== '' ? def.unit.trim() : null,
  }));
}

export interface ValidateValuesOptions {
  /**
   * Whether leaving a `required` parameter blank is an error. Default true.
   *
   * The server turns this off for a patch that says nothing about a holding's
   * shape (a name or value edit): adding a required parameter to a category
   * must not make every existing holding unsavable, including for edits that
   * have nothing to do with it.
   *
   * It is an option HERE rather than a filter at the call site because "blank"
   * is defined by this function -- an empty string counts, and so does a
   * missing key. A caller re-deriving that from the returned values cannot tell
   * a blank apart from a value that failed its type check, and would silence
   * both.
   */
  requireFilled?: boolean;
}

export interface FieldValueValidation {
  /** The values to store: coerced, trimmed, and stripped of keys the category no longer defines. */
  values: AssetFieldValues;
  /** Keyed by field key. Empty when everything passed. */
  errors: Record<string, string>;
}

/**
 * Checks and normalises a holding's parameter VALUES against its category.
 *
 * Three behaviours worth knowing before changing this:
 *
 *  - Keys the category does not define are DROPPED, not rejected. A field
 *    removed from the category while someone had the form open should not make
 *    their save fail; the value simply stops being meaningful.
 *  - Numbers accept a numeric string, because that is what an <input> produces.
 *    The stored value is always a number, so sums never meet '1200'.
 *  - An empty string is the same as "not filled in" and stores null, which is
 *    what makes `required` a single check rather than two.
 */
export function validateFieldValues(
  defs: readonly AssetFieldDef[],
  raw: Readonly<Record<string, unknown>> | null | undefined,
  options: ValidateValuesOptions = {},
): FieldValueValidation {
  const requireFilled = options.requireFilled ?? true;
  const values: AssetFieldValues = {};
  const errors: Record<string, string> = {};
  const source = raw ?? {};

  for (const def of defs) {
    const input = source[def.key];
    const isBlank = input === undefined || input === null || (typeof input === 'string' && input.trim() === '');

    if (isBlank) {
      if (def.required && requireFilled) errors[def.key] = `${def.label}は必須です`;
      values[def.key] = null;
      continue;
    }

    switch (def.type) {
      case 'number': {
        // Number('') is 0, which is why the blank case above has to run first.
        const parsed = typeof input === 'number' ? input : Number(String(input).trim());
        if (!Number.isFinite(parsed)) {
          errors[def.key] = `${def.label}は数値で入力してください`;
          values[def.key] = null;
        } else {
          values[def.key] = parsed;
        }
        break;
      }
      case 'date': {
        const text = String(input).trim();
        if (!ISO_DATE_PATTERN.test(text)) {
          errors[def.key] = `${def.label}は yyyy-MM-dd 形式で入力してください`;
          values[def.key] = null;
        } else {
          values[def.key] = text;
        }
        break;
      }
      default: {
        const text = String(input).trim();
        if (text.length > MAX_FIELD_TEXT_LENGTH) {
          errors[def.key] = `${def.label}は ${MAX_FIELD_TEXT_LENGTH} 文字までです`;
        }
        values[def.key] = text.slice(0, MAX_FIELD_TEXT_LENGTH);
        break;
      }
    }
  }

  return { values, errors };
}

/** True when a validation result has nothing to report. */
export function hasNoErrors(errors: Record<string, string>): boolean {
  return Object.keys(errors).length === 0;
}

/** Display form for one stored value. Keeps list and detail rendering identical. */
export function formatFieldValue(def: AssetFieldDef, value: AssetFieldValue): string {
  if (value === null || value === '') return '—';

  // A stored value that does not fit the definition's type should be readable,
  // not 'NaN'. reshapeFieldValues normalises holdings whenever a definition
  // changes, so this is the belt to that braces -- a row written before that
  // existed, or edited outside the application.
  const numeric = def.type === 'number' ? Number(value) : Number.NaN;
  const text = Number.isFinite(numeric) ? numeric.toLocaleString('ja-JP') : String(value);
  return def.unit ? `${text} ${def.unit}` : text;
}

// ---------------------------------------------------------------------------
// Reading back what is stored.
//
// The database columns are JSONB with a CHECK that only proves "array" and
// "object". Everything finer -- that an element really is a field definition --
// is enforced on the way IN, by the validators above. These two functions are
// the matching guard on the way OUT, so a row written by an older version of
// this code, by a migration, or by hand in psql cannot reach the UI as a shape
// it will crash on.
// ---------------------------------------------------------------------------

const FIELD_TYPES: readonly AssetFieldType[] = ['text', 'number', 'date'];

function isFieldDef(value: unknown): value is AssetFieldDef {
  if (typeof value !== 'object' || value === null) return false;
  const candidate = value as Partial<AssetFieldDef>;
  return (
    typeof candidate.key === 'string' &&
    FIELD_KEY_PATTERN.test(candidate.key) &&
    typeof candidate.label === 'string' &&
    typeof candidate.type === 'string' &&
    FIELD_TYPES.includes(candidate.type as AssetFieldType)
  );
}

/** Anything unrecognised is dropped rather than thrown on: one bad row must not empty the view. */
export function coerceFieldDefs(raw: unknown): AssetFieldDef[] {
  if (!Array.isArray(raw)) return [];
  return raw.filter(isFieldDef).map((def) => ({
    key: def.key,
    label: def.label,
    type: def.type,
    // Tolerates rows written before a flag existed; absent means "not required".
    required: def.required === true,
    unit: typeof def.unit === 'string' && def.unit !== '' ? def.unit : null,
  }));
}

export function coerceFieldValues(raw: unknown): AssetFieldValues {
  if (typeof raw !== 'object' || raw === null || Array.isArray(raw)) return {};
  const values: AssetFieldValues = {};
  for (const [key, value] of Object.entries(raw as Record<string, unknown>)) {
    if (typeof value === 'string' || typeof value === 'number') {
      values[key] = value;
    } else if (value === null) {
      values[key] = null;
    }
    // Anything else (a nested object, a boolean) has no renderer and is dropped.
  }
  return values;
}
